name: Docker Image CI CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: runninglearner/recipesoup:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull Latest Docker Image
      run: sudo docker pull runninglearner/recipesoup:latest

    - name: Restart app using Docker Compose
      run: |
        cd /home/adminuser/SetupRecipeSoup
        sudo docker-compose down
        sudo docker-compose up -d
